"""Build docs/DIAGNOSIS_REALISTIC_REPORT.md and the figure from results.csv only.

Every number in the report is computed here from examples/diagnosis_realistic_figures/
results.csv (and sanity.csv).  Deltas are training-time(u) - training-time(u=0) for the
same policy, probability and multiplier, so positive = slower.  Intervals are 95%
Student-t intervals on the seed-wise paired differences (n-1 df); pairing is by seed
only and gives little variance reduction (see "Pairing" in the report).

Usage:
    python3 examples/diagnosis_realistic_report.py --print-only   # inspect, write nothing
    python3 examples/diagnosis_realistic_report.py                # write report + figure
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import statistics
import sys
from collections import defaultdict

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from scipy import stats as sps  # noqa: E402

_here = os.path.dirname(os.path.abspath(__file__))
_root = os.path.dirname(_here)
FIG_DIR = os.path.join(_here, "diagnosis_realistic_figures")
RESULTS_CSV = os.path.join(FIG_DIR, "results.csv")
SANITY_CSV = os.path.join(FIG_DIR, "sanity.csv")
FIG_PATH = os.path.join(FIG_DIR, "delta_vs_uncertainty.png")
REPORT = os.path.join(_root, "docs", "DIAGNOSIS_REALISTIC_REPORT.md")

POLICIES = ["Random", "FFF_oracle", "FAFF"]
POLICY_LABEL = {"Random": "Random", "FFF_oracle": "FFF (oracle)",
                "FAFF": "FAFF (attributed)"}
UNCS = [0.0, 0.1, 0.2, 0.3, 0.5]
MULTS = [3.0, 5.0, 10.0]
PROBS = {0.8: MULTS, 1.0: [5.0]}
NUMERIC = ["training_time_hrs", "etr", "systematic_failures", "misattributed_repairs",
           "nonfaulty_repairs", "faulty_in_pool_timeavg", "faulty_in_active_timeavg"]


def load(path):
    rows = list(csv.DictReader(open(path, newline="")))
    data = defaultdict(dict)  # (prob, mult, policy, unc) -> rep -> row
    for r in rows:
        k = (float(r["diagnosis_probability"]), float(r["multiplier"]), r["policy"],
             float(r["diagnosis_uncertainty"]))
        data[k][int(r["rep"])] = r
    return rows, data


def vals(cell, field):
    return [float(cell[rep][field]) for rep in sorted(cell)]


def mean_ci(x):
    n = len(x)
    m = statistics.mean(x)
    if n < 2:
        return m, float("nan"), n
    half = sps.t.ppf(0.975, n - 1) * statistics.stdev(x) / math.sqrt(n)
    return m, half, n


def paired(a_cell, b_cell, field="training_time_hrs"):
    """Return (mean(a-b), half-width, n, corr(a,b)) over shared reps."""
    reps = sorted(set(a_cell) & set(b_cell))
    a = [float(a_cell[r][field]) for r in reps]
    b = [float(b_cell[r][field]) for r in reps]
    d = [x - y for x, y in zip(a, b)]
    m, half, n = mean_ci(d)
    corr = float(sps.pearsonr(a, b)[0]) if n > 2 else float("nan")
    return m, half, n, corr


def fmt_ci(m, half, digits=1):
    return f"{m:+.{digits}f} ± {half:.{digits}f}"


def build(data, rows, sanity_rows):
    out = []
    w = out.append
    corrs = []

    # ---- provenance ----
    commits = sorted({r["git_commit"][:10] for r in rows})
    w("## 1. Provenance\n")
    w(f"- Results: `examples/diagnosis_realistic_figures/results.csv` ({len(rows)} rows), "
      f"generated by `examples/diagnosis_realistic_sweep.py` at commit(s) "
      f"{', '.join('`' + c + '`' for c in commits)}; this report is generated by "
      f"`examples/diagnosis_realistic_report.py` from that CSV only.")
    w(f"- N_REPS = {rows[0]['n_reps']} per cell/policy, seeds "
      f"{rows[0]['base_seed']}..{int(rows[0]['base_seed']) + int(rows[0]['n_reps']) - 1} "
      f"(same seed set for every cell and policy), all with `NeverRemove`; full `Params` "
      f"are stored per row.")
    incomplete = [(k, len(v)) for k, v in data.items() if len(v) != int(rows[0]["n_reps"])]
    w(f"- Cells with fewer replications than N_REPS: {len(incomplete)}.\n")

    # ---- sanity ----
    w("## 2. Sanity check (`sanity.csv`)\n")
    w("Random + NeverRemove, `config.yaml` defaults, uncertainty 0, seeds 42-71 "
      "(30 replications). `SIMULATION_REPORT.md` reports 9,872.90 h at probability 1.0, "
      "and these rows are bit-identical to the golden values in "
      "`tests/data/prefix_golden.json`.\n")
    w("| diagnosis_probability | n | mean (h) | 95% CI half-width (h) |")
    w("|---|---|---|---|")
    for pr in ("1.0", "0.8"):
        t = [float(r["training_time_hrs"]) for r in sanity_rows
             if r["diagnosis_probability"] == pr]
        m, h, n = mean_ci(t)
        w(f"| {pr} | {n} | {m:.4f} | {h:.2f} |")
    w("")

    # ---- main tables ----
    w("## 3. Results\n")
    w("Δ = mean paired difference vs the uncertainty-0 cell of the same policy "
      "(hours; % of that cell's mean). `misattr.` = repairs sent to a server that did "
      "not actually fail; `non-faulty` = repairs submitted for a server with "
      "`is_bad == False` (includes ordinary random failures); `faulty pool`/`faulty "
      "active` = time-averaged number of `is_bad` servers in the working pool / in the "
      "active job, sampled every 360 simulated minutes.\n")
    for prob, mults in PROBS.items():
        for mult in mults:
            w(f"### diagnosis_probability = {prob}, multiplier = {mult:g}\n")
            w("| policy | unc | mean (h) ± 95% CI | Δ vs unc 0 (h) ± 95% CI | Δ % | ETR | "
              "syst. fail. | misattr. | non-faulty | faulty pool | faulty active |")
            w("|---|---|---|---|---|---|---|---|---|---|---|")
            for pol in POLICIES:
                base = data.get((prob, mult, pol, 0.0))
                for u in UNCS:
                    cell = data.get((prob, mult, pol, u))
                    if not cell:
                        continue
                    m, h, _ = mean_ci(vals(cell, "training_time_hrs"))
                    if u == 0.0 or not base:
                        d_txt, pct_txt = "—", "—"
                    else:
                        dm, dh, _, c = paired(cell, base)
                        corrs.append(c)
                        d_txt = fmt_ci(dm, dh)
                        bmean = statistics.mean(vals(base, "training_time_hrs"))
                        pct_txt = f"{100 * dm / bmean:+.2f}%"
                    means = {f: statistics.mean(vals(cell, f)) for f in NUMERIC}
                    w(f"| {POLICY_LABEL[pol]} | {u} | {m:.1f} ± {h:.1f} | {d_txt} | "
                      f"{pct_txt} | {means['etr']:.4f} | {means['systematic_failures']:.0f} | "
                      f"{means['misattributed_repairs']:.0f} | {means['nonfaulty_repairs']:.0f} | "
                      f"{means['faulty_in_pool_timeavg']:.1f} | "
                      f"{means['faulty_in_active_timeavg']:.1f} |")
            w("")

    # ---- policy contrasts ----
    w("## 4. Policy contrasts (paired by seed, hours, negative = first policy faster)\n")
    w("| prob | mult | unc | FFF − Random | FAFF − Random | FAFF − FFF |")
    w("|---|---|---|---|---|---|")
    for prob, mults in PROBS.items():
        for mult in mults:
            for u in UNCS:
                c = {p: data.get((prob, mult, p, u)) for p in POLICIES}
                if not all(c.values()):
                    continue
                a = paired(c["FFF_oracle"], c["Random"])
                b = paired(c["FAFF"], c["Random"])
                d = paired(c["FAFF"], c["FFF_oracle"])
                w(f"| {prob} | {mult:g} | {u} | {fmt_ci(a[0], a[1])} | "
                  f"{fmt_ci(b[0], b[1])} | {fmt_ci(d[0], d[1])} |")
    w("")

    w("## 5. Pairing\n")
    w("All components share one RNG, and `rng.random() < diagnosis_uncertainty` is only "
      "drawn when uncertainty > 0, so runs with the same seed diverge at the first "
      "failure (and Random vs FFF at the first host selection). Only the initial "
      "bad-server layout is shared. Mean seed-wise correlation between an "
      f"uncertainty-u run and its uncertainty-0 counterpart: "
      f"{statistics.mean(corrs):+.2f} (n = {len(corrs)} comparisons), i.e. pairing "
      "gives essentially no variance reduction; the paired-t intervals are valid but "
      "not tighter than unpaired ones.\n")

    w("## 6. Accounting identity\n")
    w("In every run, training time equals job_length + total_failures × recovery_time "
      "+ host_selection_count × host_selection_time + preemption_count × "
      "preemption_wait_time (there are no job stalls in this sweep). AIReSim charges "
      "exactly one `recovery_time` per failure and no "
      "lost work since the last checkpoint. Any effect of diagnosis quality or policy on "
      "training time is therefore exactly its effect on the number of failures.\n")
    res = identity_residuals(rows)
    w(f"Maximum absolute residual of that identity over all {len(rows)} runs: "
      f"{max(res):.2e} h.\n")
    w("| prob | mult | policy | unc | Δ time (h) | Δ failures | Δ failures × recovery (h) |")
    w("|---|---|---|---|---|---|---|")
    for prob, mult, pol, u, dT, dF, pred, _ in mechanism_rows(data):
        w(f"| {prob} | {mult:g} | {POLICY_LABEL[pol]} | {u} | {dT:+.1f} | {dF:+.1f} | "
          f"{pred:+.1f} |")
    w("")
    w("The two columns differ only by the host-selection and preemption-wait terms "
      "(a few minutes each).\n")

    return out, corrs


def mechanism_rows(data):
    """Per cell (u > 0): paired Δ training time vs Δ total_failures × recovery_time.

    Returns a list of (prob, mult, policy, u, dT_hours, dF, predicted_hours, ratio).
    recovery_time is read from the stored Params (minutes).
    """
    import json
    out = []
    for prob, mults in PROBS.items():
        for mult in mults:
            for pol in POLICIES:
                base = data.get((prob, mult, pol, 0.0))
                if not base:
                    continue
                rec_min = json.loads(next(iter(base.values()))["params_json"])["recovery_time"]
                for u in UNCS:
                    if u == 0.0 or (prob, mult, pol, u) not in data:
                        continue
                    cell = data[(prob, mult, pol, u)]
                    dT, _, _, _ = paired(cell, base)
                    dF, _, _, _ = paired(cell, base, field="total_failures")
                    pred = dF * rec_min / 60.0
                    ratio = dT / pred if pred else float("nan")
                    out.append((prob, mult, pol, u, dT, dF, pred, ratio))
    return out


def identity_residuals(rows):
    """|training_time - (job_length + failures*recovery + host_selections*hs_time
    + preemptions*preemption_wait)| in hours."""
    import json
    out = []
    for r in rows:
        p = json.loads(r["params_json"])
        pred = (p["job_length"] + float(r["total_failures"]) * p["recovery_time"]
                + float(r["host_selection_count"]) * p["host_selection_time"]
                + float(r["preemption_count"]) * p["preemption_wait_time"]) / 60.0
        out.append(abs(float(r["training_time_hrs"]) - pred))
    return out


def design_stats(rows):
    """Mean full host selections and mean failures per run, over all rows."""
    hs = [float(r["host_selection_count"]) for r in rows]
    tf = [float(r["total_failures"]) for r in rows]
    return statistics.mean(hs), min(hs), max(hs), statistics.mean(tf)


def headroom_mechanism(data, rows):
    """Headroom vs. bad population, and active-vs-pool faulty-server benching.

    `Scheduler.do_host_selection` re-picks the entire job from the available pool, so
    a full selection can exclude every server the policy regards as bad, up to headroom
    (working_pool_size - job_size - warm_standbys). This computes that bound and the
    observed benching (faulty_in_active_timeavg) at diagnosis_probability=1.0,
    multiplier=5.0, uncertainty=0.0 -- the paper-default cell in this sweep.
    """
    import json

    p = json.loads(rows[0]["params_json"])
    headroom = p["working_pool_size"] - p["job_size"] - p["warm_standbys"]
    bad_pop = p["working_pool_size"] * p["systematic_failure_fraction"]
    base = data[(1.0, 5.0, "Random", 0.0)]
    fff = data[(1.0, 5.0, "FFF_oracle", 0.0)]
    return dict(
        headroom=headroom, bad_pop=bad_pop, working_pool_size=p["working_pool_size"],
        act_random=statistics.mean(vals(base, "faulty_in_active_timeavg")),
        act_fff=statistics.mean(vals(fff, "faulty_in_active_timeavg")),
        pool_random=statistics.mean(vals(base, "faulty_in_pool_timeavg")),
        pool_fff=statistics.mean(vals(fff, "faulty_in_pool_timeavg")),
    )


def criterion(data):
    """Pre-registered test: Random+NeverRemove, prob 0.8, multiplier 5."""
    res = {}
    base = data[(0.8, 5.0, "Random", 0.0)]
    bmean = statistics.mean(vals(base, "training_time_hrs"))
    for u in (0.1, 0.2):
        cell = data[(0.8, 5.0, "Random", u)]
        dm, dh, n, _ = paired(cell, base)
        pct = 100 * dm / bmean
        res[u] = dict(delta=dm, half=dh, pct=pct, pct_lo=100 * (dm - dh) / bmean,
                      pct_hi=100 * (dm + dh) / bmean, excludes_zero=(dm - dh > 0 or dm + dh < 0),
                      raises=dm > 0, n=n)
    res["met"] = (res[0.2]["pct"] >= 1.0) and (res[0.2]["delta"] - res[0.2]["half"] > 0)
    return res


def faff_assessment(data):
    """Oracle FFF benefit at u=0 and whether FAFF keeps it (prob 0.8, all multipliers)."""
    out = {}
    for mult in MULTS:
        r = data[(0.8, mult, "Random", 0.0)]
        f = data[(0.8, mult, "FFF_oracle", 0.0)]
        m, h, _, _ = paired(f, r)  # FFF - Random
        out[mult] = dict(fff_minus_random=m, half=h, benefit=(m + h < 0))
    return out


def contrast_counts(data):
    """(# of §4 contrasts whose paired 95% CI excludes 0, total # of contrasts)."""
    sig = tot = 0
    for prob, mults in PROBS.items():
        for mult in mults:
            for u in UNCS:
                c = {p: data.get((prob, mult, p, u)) for p in POLICIES}
                if not all(c.values()):
                    continue
                for a, b in (("FFF_oracle", "Random"), ("FAFF", "Random"),
                             ("FAFF", "FFF_oracle")):
                    m, h, n, _ = paired(c[a], c[b])
                    if a == "FAFF" and b == "FFF_oracle" and prob == 1.0 and u == 0.0:
                        continue  # identical by construction (counters equal)
                    tot += 1
                    sig += int(abs(m) > h)
    return sig, tot


def verdict(data, rows):
    c = criterion(data)
    fa = faff_assessment(data)
    u2, u1 = c[0.2], c[0.1]
    lines = []
    lines.append(
        f"**Misattribution matters at realistic parameters: "
        f"{'YES' if c['met'] else 'NO'} (pre-registered criterion).** For Random + "
        f"NeverRemove at multiplier 5 and diagnosis_probability 0.8, uncertainty 0.2 "
        f"changes mean training time by {u2['delta']:+.1f} h "
        f"({u2['pct']:+.2f}%; 95% CI {u2['pct_lo']:+.2f}% to {u2['pct_hi']:+.2f}%), and "
        f"uncertainty 0.1 by {u1['delta']:+.1f} h ({u1['pct']:+.2f}%; 95% CI "
        f"{u1['pct_lo']:+.2f}% to {u1['pct_hi']:+.2f}%); the criterion required a rise of "
        f"at least 1% with a CI excluding zero.")
    # dose-response beyond the pre-registered range (descriptive, not part of the criterion)
    hi = {}
    for m in (5.0, 10.0):
        base = data[(0.8, m, "Random", 0.0)]
        bmean = statistics.mean(vals(base, "training_time_hrs"))
        dm, dh, _, _ = paired(data[(0.8, m, "Random", 0.5)], base)
        hi[m] = (100 * dm / bmean, 100 * (dm - dh) / bmean, 100 * (dm + dh) / bmean)
    lines.append(
        "The effect is nonetheless small but detectable, and it grows with uncertainty: "
        f"for Random at uncertainty 0.5 (outside the pre-registered range) training time "
        f"rises {hi[5.0][0]:+.2f}% (95% CI {hi[5.0][1]:+.2f}% to {hi[5.0][2]:+.2f}%) at "
        f"multiplier 5 and {hi[10.0][0]:+.2f}% ({hi[10.0][1]:+.2f}% to {hi[10.0][2]:+.2f}%) "
        "at multiplier 10.")
    any_benefit = [m for m, v in fa.items() if v["benefit"]]
    lo = min(v["fff_minus_random"] - v["half"] for v in fa.values())
    ref = statistics.mean(vals(data[(0.8, 5.0, "Random", 0.0)], "training_time_hrs"))
    n_sig, n_tot = contrast_counts(data)
    hs_mean, hs_min, hs_max, tf_mean = design_stats(rows)
    if any_benefit:
        lines.append("Oracle FFF beats Random at uncertainty 0 (paired 95% CI excludes 0) at "
                     f"multiplier(s) {', '.join(f'{m:g}' for m in any_benefit)}; see §4 for "
                     "whether FAFF keeps that benefit as uncertainty rises.")
    else:
        lines.append(
            "Whether FewestAttributedFailuresFirst retains the benefit of oracle FFF is moot "
            "here: oracle FFF shows no measurable benefit over Random even at uncertainty 0 "
            "(paired 95% CIs include 0 at all three multipliers; a benefit larger than "
            f"{-lo:.0f} h, about {-100 * lo / ref:.1f}% of training time, is excluded). "
            f"Across all {n_tot} paired policy contrasts in §4, {n_sig} "
            f"{'has' if n_sig == 1 else 'have'} a 95% CI "
            f"excluding zero (about {0.05 * n_tot:.0f} expected by chance, no multiplicity "
            f"adjustment).")
        mech = headroom_mechanism(data, rows)
        cover_pct = 100 * mech["headroom"] / mech["bad_pop"]
        bad_pct = 100 * mech["bad_pop"] / mech["working_pool_size"]
        lines.append(
            "This null result is not because the scheduling policy is rarely consulted. "
            "`Scheduler.do_host_selection` re-picks the *entire* job "
            "(`job_size + warm_standbys`) from the available pool every time it runs -- "
            f"it happened {hs_mean:.1f} times per run here (range {hs_min:.0f}"
            f"–{hs_max:.0f}) -- so one full selection can bench every server the "
            "policy currently regards as bad, up to the pool's headroom "
            "(`working_pool_size - job_size - warm_standbys`). Between full selections, "
            "`Scheduler.swap_in_standby` replaces a failed active server with the oldest "
            "warm standby, FIFO, without consulting the policy; a full selection is "
            "re-triggered only once standbys run out. At these parameters headroom is "
            f"{mech['headroom']:.0f} servers against an initial bad population of "
            f"~{mech['bad_pop']:.0f} ({bad_pct:.0f}% of the pool) -- only {cover_pct:.1f}% "
            "of the bad population can be excluded even by a perfectly policy-aware "
            "selection, and that population shrinks further as the run progresses and "
            "repairs cure it out (`SIMULATION_REPORT.md` §5a). Both bound the "
            "benefit independent of how often full selection happens. The data agree: "
            "time-averaged faulty servers in the active job are statistically "
            f"indistinguishable between oracle FFF ({mech['act_fff']:.1f}) and Random "
            f"({mech['act_random']:.1f}) at these parameters. Contrast the stress regime "
            "(`SCHEDULING_COMPARISON_REPORT.md`), where headroom (488 servers) exceeds "
            "the entire initial bad population (~368) and FewestFailuresFirst visibly "
            "benches bad servers (faulty-in-active time-average 129.7 vs Random's 170.9, "
            "saving ~272 h) -- confirming the mechanism works when headroom allows it, "
            "and that its absence here, not rare consultation, is why FFF and FAFF show "
            "no benefit at these parameters. FewestAttributedFailuresFirst has not been "
            "tested in the stress regime.")
    worst = max(identity_residuals(rows))
    lines.append(
        "The misattribution cost is an accounting consequence of extra failures. In "
        "AIReSim, training time is exactly job_length + failures × recovery_time + "
        "host selections × host_selection_time + preemptions × preemption_wait_time "
        "(largest residual over all runs "
        f"{worst:.1e} h; §6). Misattribution leaves faulty servers unrepaired, they fail "
        "again, and each extra failure costs one recovery. The model charges no lost "
        "work since the last checkpoint, so a failure's cost does not depend on when it "
        "occurs.")
    return lines, c, fa


def make_figure(data):
    fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)
    colors = {"Random": "#333333", "FFF_oracle": "#d62728", "FAFF": "#1f77b4"}
    for ax, mult in zip(axes, MULTS):
        for pol in POLICIES:
            base = data[(0.8, mult, pol, 0.0)]
            xs, ys, es = [], [], []
            for u in UNCS:
                cell = data.get((0.8, mult, pol, u))
                if not cell:
                    continue
                if u == 0.0:
                    dm, dh = 0.0, 0.0
                else:
                    dm, dh, _, _ = paired(cell, base)
                xs.append(u)
                ys.append(dm)
                es.append(dh)
            ax.errorbar(xs, ys, yerr=es, marker="o", capsize=3, label=POLICY_LABEL[pol],
                        color=colors[pol])
        ax.axhline(0, color="grey", lw=0.8)
        ax.set_title(f"multiplier {mult:g} (diagnosis_probability 0.8)")
        ax.set_xlabel("diagnosis_uncertainty")
    axes[0].set_ylabel("Δ training time vs uncertainty 0 (h), 95% CI")
    axes[0].legend()
    fig.tight_layout()
    fig.savefig(FIG_PATH, dpi=150)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--print-only", action="store_true")
    a = ap.parse_args()
    rows, data = load(RESULTS_CSV)
    sanity_rows = list(csv.DictReader(open(SANITY_CSV, newline="")))
    body, corrs = build(data, rows, sanity_rows)
    vlines, crit, fa = verdict(data, rows)
    text = "\n".join(body)
    print(text)
    print("\n--- criterion ---")
    for u in (0.1, 0.2):
        print(u, crit[u])
    print("met:", crit["met"])
    print("--- oracle FFF vs Random at u=0 ---")
    for m, v in fa.items():
        print(m, v)
    print("--- verdict lines ---")
    print("\n".join(vlines))
    if a.print_only:
        return
    make_figure(data)
    header = ("# Does Diagnosis Uncertainty Matter at Realistic Parameters?\n\n"
              "**Configuration:** `config.yaml` (DSN'26 Table I defaults) with only "
              "`diagnosis_uncertainty`, the systematic-failure multiplier and "
              "`diagnosis_probability` varied; `NeverRemove` throughout. Δ is training time "
              "minus the same policy's uncertainty-0 training time (positive = slower).\n\n"
              "**Pre-registered criterion:** \"Misattribution matters at realistic "
              "parameters\" if, for Random + NeverRemove at multiplier 5, uncertainty ≤ 0.2 "
              "raises mean training time by ≥ 1% with a 95% CI excluding zero (tested at "
              "diagnosis_probability 0.8, uncertainty 0.2; uncertainty 0.1 and the "
              "probability-1.0 slice are reported but do not decide the verdict).\n\n")
    verdict_md = "## Verdict\n\n" + "\n\n".join(vlines) + "\n"
    fig_md = ("\n## Figure\n\n![Training-time delta vs uncertainty]"
              "(../examples/diagnosis_realistic_figures/delta_vs_uncertainty.png)\n")
    with open(REPORT, "w") as f:
        f.write(header + verdict_md + "\n---\n\n" + text + fig_md)
    print("wrote", REPORT, "and", FIG_PATH, file=sys.stderr)


if __name__ == "__main__":
    main()
